// Generated from macros.tex by build/macros.py
window.BOOK_MACROS = {
 "A": "\\vect{A}",
 "B": "\\vect{B}",
 "C": "\\mathcal{C}",
 "Cov": "\\operatorname{Cov}",
 "E": "\\operatorname{E}",
 "G": "\\vect{G}",
 "I": "\\vect{I}",
 "M": "\\vect{M}",
 "Mo": "\\vect{M}_0",
 "Normal": "\\mathrm{N}",
 "Null": "\\mathcal{N}",
 "Q": "\\vect{Q}",
 "R": "\\vect{R}",
 "Real": "\\mathbb{R}",
 "T": "^{\\top}",
 "V": "\\vect{V}",
 "Var": "\\operatorname{Var}",
 "W": "\\vect{W}",
 "X": "\\vect{X}",
 "Y": "\\vect{Y}",
 "Z": "\\vect{Z}",
 "argmin": "\\operatorname*{arg\\,min}",
 "bD": "\\vect{D}",
 "bH": "\\vect{H}",
 "bL": "\\vect{L}",
 "bLambda": "\\boldsymbol{\\Lambda}",
 "bP": "\\vect{P}",
 "bS": "\\vect{S}",
 "bSigma": "\\boldsymbol{\\Sigma}",
 "bT": "\\vect{T}",
 "bU": "\\vect{U}",
 "bb": "\\vect{b}",
 "bbeta": "\\boldsymbol{\\upbeta}",
 "be": "\\boldsymbol{\\upvarepsilon}",
 "bgamma": "\\boldsymbol{\\upgamma}",
 "blambda": "\\boldsymbol{\\uplambda}",
 "bm": [
  "\\boldsymbol{#1}",
  1
 ],
 "bmu": "\\boldsymbol{\\upmu}",
 "bone": "\\vect{1}",
 "br": "\\vect{r}",
 "bu": "\\vect{u}",
 "bv": "\\vect{v}",
 "bw": "\\vect{w}",
 "bz": "\\vect{z}",
 "bzero": "\\vect{0}",
 "coloneqq": "\\mathrel{:=}",
 "diag": "\\operatorname{diag}",
 "dirsum": "\\oplus",
 "eqqcolon": "\\mathrel{=:}",
 "ginv": "^{-}",
 "hY": "\\hat{\\Y}",
 "hbeta": "\\hat{\\bbeta}",
 "he": "\\hat{\\be}",
 "iid": "\\overset{\\text{iid}}{\\sim}",
 "inner": [
  "\\langle #1,#2\\rangle",
  2
 ],
 "norm": [
  "\\lVert #1\\rVert",
  1
 ],
 "perpc": "^{\\perp}",
 "rank": "\\operatorname{rank}",
 "spn": "\\operatorname{span}",
 "tr": "\\operatorname{tr}",
 "vecop": "\\operatorname{vec}",
 "vect": [
  "\\mathbf{#1}",
  1
 ],
 "x": "\\vect{x}",
 "y": "\\vect{y}"
};
