/**
 * Dependency graph page (graph.html, generated by build/extras.py).
 *
 * Nodes are chapters; an edge A -> B means a *proof* in B uses a result from A, with the
 * arrow's width growing with the number of such proofs. Citations made in passing -- a
 * statement, a remark, an exercise, a solution -- are carried in the data as `soft` and are
 * not part of the skeleton, and neither is a dependency that a longer chain already implies.
 * Hovering a chapter brings both back, as dashed arrows and as counts in the panel beside
 * the graph. Layered layout (dagre) flowing top to bottom; clicking a chapter opens it.
 *
 * The overview is the default, but the graph is not what a reader acts on: one section is.
 * The picker holds every section of the book and every reader profile, and choosing one
 * dims the chapters its reading path never reaches and counts the sections it needs from
 * each of the rest. The closures are precomputed in graph.json, per chapter rather than
 * per section, which is what keeps 236 of them small.
 */

const CYTOSCAPE_URL = 'https://cdn.jsdelivr.net/npm/cytoscape@3.34.3/dist/cytoscape.min.js';
const DAGRE_URL = 'https://cdn.jsdelivr.net/npm/cytoscape-dagre@4.0.1/dist/cytoscape-dagre.js';

function loadScript(src) {
    return new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = src;
        script.onload = resolve;
        script.onerror = () => reject(new Error(`Could not load ${src}`));
        document.head.append(script);
    });
}

const cssVar = name => getComputedStyle(document.documentElement).getPropertyValue(name).trim();
const escapeHtml = text => String(text).replace(
    /[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const basePath = () => document.querySelector('meta[name="asset-prefix"]')?.content || './';

function graphStyle() {
    const ink = cssVar('--ink'), paper = cssVar('--paper'),
        accent = cssVar('--accent'), rule = cssVar('--rule-strong');
    return [
        {
            selector: 'node',
            style: {
                'shape': 'round-rectangle',
                'width': 'label', 'height': 'label', 'padding': '12px',
                'background-color': paper,
                'border-width': 2, 'border-color': accent,
                'label': 'data(label)', 'color': ink,
                'font-family': 'STIX Two Text, Times New Roman, serif', 'font-size': 14,
                'text-wrap': 'wrap', 'text-max-width': 150, 'text-valign': 'center', 'text-halign': 'center',
                'transition-property': 'opacity, border-width', 'transition-duration': '150ms',
            },
        },
        {
            selector: 'edge',
            style: {
                'width': 'data(width)', 'line-color': rule, 'target-arrow-color': rule,
                'target-arrow-shape': 'triangle', 'arrow-scale': 1,
                'curve-style': 'bezier',
                'transition-property': 'opacity, line-color', 'transition-duration': '150ms',
            },
        },
        {
            // A dropped dependency arcs out to one side, so it does not hide under the spine
            selector: 'edge.implied',
            style: {
                'display': 'none', 'line-style': 'dashed', 'line-dash-pattern': [6, 4],
                'width': 1.2, 'opacity': 0.6,
                'curve-style': 'unbundled-bezier',
                'control-point-distances': 'data(bow)', 'control-point-weights': 0.5,
            },
        },
        {
            selector: 'edge.implied.shown',
            style: {
                'display': 'element', 'opacity': 0.85, 'width': 1.6,
                'line-color': accent, 'target-arrow-color': accent,
            },
        },
        { selector: '.faded', style: { 'opacity': 0.15 } },
        { selector: 'node.focus', style: { 'border-width': 3.5, 'background-color': cssVar('--hover-wash') || paper } },
        { selector: 'edge.path', style: { 'line-color': accent, 'target-arrow-color': accent } },
        { selector: 'node:active, node:selected', style: { 'overlay-opacity': 0 } },
        // A chosen target dims what its reading path never reaches. Kept separate from
        // `.faded`, which hover adds and removes, so the two do not fight each other.
        { selector: '.off-path', style: { 'opacity': 0.12 } },
        { selector: 'node.on-path', style: { 'border-color': accent, 'border-width': 3 } },
    ];
}

async function init() {
    const container = document.getElementById('dependency-graph');
    if (!container) return;
    const preview = document.querySelector('.graph-preview');

    let data;
    try {
        [data] = await Promise.all([
            fetch(basePath() + container.dataset.graph, { cache: 'no-cache' }).then(r => r.json()),
            loadScript(CYTOSCAPE_URL).then(() => loadScript(DAGRE_URL)),
        ]);
    } catch (error) {
        container.textContent = `The graph could not be loaded: ${error.message}`;
        container.classList.add('graph-error');
        return;
    }
    window.cytoscape.use(window.cytoscapeDagre);
    const rank = Object.fromEntries(data.nodes.map(n => [n.id, n.chapterNumber ?? 0]));

    const cy = window.cytoscape({
        container,
        elements: [
            ...data.nodes.map(n => ({ data: { ...n, label: n.title ? `${n.name}\n${n.title}` : n.name } })),
            ...data.edges.map((e, i) => ({
                data: {
                    id: `e${i}`, ...e,
                    width: Math.min(6, 1 + Math.log2(1 + (e.weight || 1))),
                    // How far a dropped dependency bows out: the further apart the two
                    // chapters, the wider the arc, and consecutive arcs alternate sides
                    bow: (i % 2 ? 1 : -1) * (55 + 22 * Math.abs(
                        (rank[e.target] ?? 0) - (rank[e.source] ?? 0))),
                },
                classes: e.implied ? 'implied' : '',
            })),
        ],
        style: graphStyle(),
        minZoom: 0.2, maxZoom: 2.5, wheelSensitivity: 0.2,
        autoungrabify: true, boxSelectionEnabled: false,
    });

    container.cyGraph = cy;  // a handle for the console and for the hover test

    // Lay out each group of connected results on its own (top to bottom), then pack the
    // groups into rows that fit the frame, largest first. Laying out everything at once puts
    // unrelated groups in one very wide row, which becomes unreadably small when fitted.
    const layout = () => {
        const groups = cy.elements(':visible').components()
            .sort((a, b) => b.nodes().length - a.nodes().length);
        const rowWidth = Math.max(container.clientWidth - 60, 400);
        const gap = 48;
        let x = 0, y = 0, rowHeight = 0;
        for (const group of groups) {
            group.layout({ name: 'dagre', rankDir: 'TB', nodeSep: 22, rankSep: 38, edgeSep: 10, animate: false, fit: false }).run();
            const box = group.boundingBox();
            if (x > 0 && x + box.w > rowWidth) {
                x = 0;
                y += rowHeight + gap;
                rowHeight = 0;
            }
            const dx = x - box.x1, dy = y - box.y1;
            group.nodes().positions(node => ({ x: node.position('x') + dx, y: node.position('y') + dy }));
            x += box.w + gap;
            rowHeight = Math.max(rowHeight, box.h);
        }
        cy.fit(cy.elements(':visible'), 24);
        const floor = 0.72;  // below this the chapter titles stop being readable
        if (cy.zoom() < floor) {  // pin the top and centre it; the reader can pan down
            cy.zoom(floor);
            const box = cy.elements(':visible').boundingBox();
            cy.pan({
                x: (container.clientWidth - box.w * floor) / 2 - box.x1 * floor,
                y: 24 - box.y1 * floor,
            });
        }
    };

    // Hover: highlight what the chapter rests on and what rests on it, and reveal the
    // direct dependencies the reduction dropped as dashed arrows
    let hovered = null;
    cy.on('mouseover', 'node', event => {
        const node = event.target;
        hovered = node.id();
        const dropped = node.connectedEdges('.implied');
        const related = node.predecessors().union(node.successors()).union(node)
            .union(dropped).union(dropped.connectedNodes());
        cy.batch(() => {
            cy.elements().addClass('faded');
            dropped.addClass('shown');
            related.removeClass('faded');
            related.edges().not('.implied').addClass('path');
            node.addClass('focus');
        });
        container.style.cursor = 'pointer';
        showPreview(node);
    });
    cy.on('mouseout', 'node', () => {
        hovered = null;
        cy.batch(() => cy.elements().removeClass('faded path focus shown'));
        container.style.cursor = '';
    });
    cy.on('tap', 'node', event => {
        window.location.href = basePath() + event.target.data('url');
    });

    function showPreview(node) {
        const d = node.data();
        // Edges into the node are the chapters it cites; edges out are the chapters citing it
        const edgesBy = (direction, drawn) => node.connectedEdges()
            .filter(e => (direction === 'in' ? e.target() : e.source()).id() === node.id())
            .filter(e => drawn === null || e.hasClass('implied') !== drawn);
        const other = (direction, e) => (direction === 'in' ? e.source() : e.target());
        const list = (direction, drawn, field = 'weight') => edgesBy(direction, drawn)
            .map(e => ({ node: other(direction, e), weight: e.data(field) || 0 }))
            .filter(({ weight }) => weight > 0)
            .sort((a, b) => a.node.data('chapterNumber') - b.node.data('chapterNumber'))
            .map(({ node: n, weight }) => `${n.data('name')} (${weight})`)
            .join(', ');
        const citations = (direction, field = 'weight') => edgesBy(direction, null)
            .reduce((total, e) => total + (e.data(field) || 0), 0);
        preview.hidden = false;
        preview.innerHTML = `
            <div class="graph-preview-name"></div>
            <div class="graph-preview-title"></div>
            <div class="graph-preview-body"></div>
            <div class="graph-preview-meta"></div>`;
        preview.querySelector('.graph-preview-name').textContent = d.name;
        preview.querySelector('.graph-preview-title').textContent = d.title;
        const line = (label, text, extra = '') =>
            text ? `<p class="${extra}"><strong>${label}:</strong> ${text}</p>` : '';
        preview.querySelector('.graph-preview-body').innerHTML =
            (line('Proofs here rest on', list('in', true))
                || '<p><strong>Proofs here rest on:</strong> nothing earlier</p>')
            + line('And, by a longer chain', list('in', false), 'graph-preview-implied')
            + line('Cites outside a proof', list('in', null, 'soft'), 'graph-preview-implied')
            + (line('Proved from, later', list('out', true))
                || '<p><strong>Proved from, later:</strong> nothing yet</p>')
            + line('And, by a longer chain', list('out', false), 'graph-preview-implied');
        preview.querySelector('.graph-preview-meta').textContent =
            `${d.sections} sections · ${d.results} results · ${citations('in')} proof citations`
            + ` · ${citations('in', 'soft')} in passing`;
        preview.style.setProperty('--env-color', cssVar('--accent'));
    }

    // ---- Choose a target: dim the chapters its reading path never reaches ----
    //
    // The closure is precomputed per chapter (graph.json), so choosing a target is a
    // lookup, not a graph walk. `chapters` is what the proofs need; `extra` is what the
    // written solutions add on top, which the checkbox folds in. Keys are chapter
    // positions, not slugs, which is what keeps 236 closures to a small file.
    const picker = document.getElementById('graph-target');
    const exercises = document.getElementById('graph-exercises');
    const readout = document.querySelector('.graph-closure');
    const slugAt = index => data.nodes[index]?.id;

    function fillPicker() {
        if (!picker) return;
        const option = (value, text) => {
            const element = document.createElement('option');
            element.value = value;
            element.textContent = text;
            return element;
        };
        if (data.profiles?.length) {
            const group = document.createElement('optgroup');
            group.label = 'Reader profiles';
            for (const profile of data.profiles) group.append(option(`p:${profile.slug}`, profile.name));
            picker.append(group);
        }
        const groups = new Map();
        for (const [id, closure] of Object.entries(data.closures || {})) {
            const chapter = closure.chapter || id.split('/')[0];
            if (!groups.has(chapter)) {
                const group = document.createElement('optgroup');
                group.label = data.nodes.find(n => n.id === chapter)?.title || chapter;
                groups.set(chapter, group);
                picker.append(group);
            }
            groups.get(chapter).append(option(id, closure.name || id));
        }
        picker.disabled = false;
    }

    function chosen() {
        const value = picker?.value || '';
        if (!value) return null;
        if (value.startsWith('p:')) {
            return (data.profiles || []).find(p => `p:${p.slug}` === value) || null;
        }
        return (data.closures || {})[value] || null;
    }

    function applyTarget() {
        const closure = chosen();
        cy.batch(() => cy.elements().removeClass('off-path on-path'));
        if (!closure) {
            if (readout) { readout.hidden = true; readout.textContent = ''; }
            return;
        }
        const withExercises = !!exercises?.checked;
        const counts = new Map();
        for (const [index, count] of Object.entries(closure.chapters || {})) {
            counts.set(slugAt(Number(index)), count);
        }
        if (withExercises) {
            for (const [index, count] of Object.entries(closure.extra || {})) {
                const slug = slugAt(Number(index));
                counts.set(slug, (counts.get(slug) || 0) + count);
            }
        }
        cy.batch(() => {
            for (const node of cy.nodes()) {
                node.addClass(counts.has(node.id()) ? 'on-path' : 'off-path');
            }
            for (const edge of cy.edges()) {
                if (!counts.has(edge.source().id()) || !counts.has(edge.target().id())) {
                    edge.addClass('off-path');
                }
            }
        });
        if (!readout) return;
        const needed = withExercises ? closure.nx : closure.n;
        const where = data.nodes
            .filter(n => counts.has(n.id))
            .map(n => `${escapeHtml(n.name)} (${counts.get(n.id)} of ${n.sections})`)
            .join(', ');
        const link = closure.url
            ? ` <a href="${basePath()}${escapeHtml(closure.url)}">`
              + `${closure.slug ? 'The full path' : 'Open the section'}</a>.`
            : '';
        readout.hidden = false;
        readout.innerHTML =
            `<strong>${escapeHtml(closure.name)}</strong> needs <strong>${needed}</strong> of the book's `
            + `${data.total} sections${withExercises ? ', exercises included' : ''}: ${where}.`
            + (withExercises ? '' : ` Working the exercises as well makes it ${closure.nx}.`)
            + link;
    }

    fillPicker();
    picker?.addEventListener('change', applyTarget);
    exercises?.addEventListener('change', applyTarget);

    // Follow the theme: restyle when the toolbar switches light/dark
    new MutationObserver(() => cy.style(graphStyle())).observe(document.documentElement, {
        attributes: true, attributeFilter: ['data-theme'],
    });

    layout();
    window.addEventListener('resize', () => cy.resize());
}

init();
